# 端口号配置
server:
  port: 8080

# 激活本地配置文件
spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/four?serverTimezone=UTC&characterEncoding=utf8&allowMultiQueries=true
    password: "123456"
    username: root
ip: localhost

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    map-underscore-to-camel-case: true
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALIYUN_ACCESS_KEY_ID:your-access-key-id}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET:your-access-key-secret}
    bucket-name: fourbucke
